app.message: Hola mundo desde gateway
server.port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:${app.eureka-port}/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
    
spring:
  cloud:
    gateway:
      routes:
        # MICROSERVICIO customers http://localhost:8080/customers/hello
        - id: customers-service
          uri: lb://customers-service
          predicates:
            - Path=/customers-service/**